# Generated by Django 2.1.1 on 2018-11-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escopo',
            name='destinatarios',
        ),
        migrations.RemoveField(
            model_name='escopo',
            name='obs_impacto_nao_entrega',
        ),
        migrations.RemoveField(
            model_name='escopo',
            name='obs_resultados',
        ),
        migrations.RemoveField(
            model_name='escopo',
            name='obs_utilizacao',
        ),
    ]
